# Generated by Django 3.0.3 on 2020-02-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200212_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beds',
            options={'verbose_name_plural': 'Beds'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name_plural': 'Income Statements'},
        ),
        migrations.AddField(
            model_name='site',
            name='city',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='site',
            name='county',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='site',
            name='postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='site',
            name='street_address_1',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='site',
            name='street_address_2',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
