# Generated by Django 3.0.3 on 2020-02-12 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200212_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beds',
            options={'ordering': ['year'], 'verbose_name_plural': 'Beds'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['year'], 'verbose_name_plural': 'Income Statements'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='stp',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['year']},
        ),
        migrations.AddField(
            model_name='site',
            name='website',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='nhs_code',
            field=models.CharField(max_length=6, verbose_name='NHS Code'),
        ),
        migrations.AlterField(
            model_name='site',
            name='stp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.STP', verbose_name='STP'),
        ),
    ]
