# Generated by Django 3.0.3 on 2020-02-12 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200212_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nhs_code', models.CharField(max_length=6, verbose_name='NHS Code')),
                ('street_address_1', models.CharField(blank=True, max_length=40)),
                ('street_address_2', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('county', models.CharField(blank=True, max_length=20)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Site', verbose_name='STP')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
