# Generated by Django 3.0.3 on 2020-02-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200212_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsite',
            name='main_location',
            field=models.BooleanField(default=False),
        ),
    ]
