# Generated by Django 3.0.3 on 2020-02-14 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200213_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_suite', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['year'], 'verbose_name_plural': 'Income Statements'},
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=20)),
                ('last', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=5)),
                ('nhs_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Site')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Position')),
            ],
        ),
    ]
